permissionset 50000 "Permission Set"
{
    Assignable = true;
    Permissions = tabledata "Customer Order Header"=RIMD,
        tabledata "Customer Order Line"=RIMD,
        tabledata "Customer Order Payment"=RIMD,
        tabledata "Posted Customer Order Header"=RIMD,
        tabledata "Posted Customer Order Line"=RIMD,
        tabledata "Posted Customer Order Payment"=RIMD,
        table "Customer Order Header"=X,
        table "Customer Order Line"=X,
        table "Customer Order Payment"=X,
        table "Posted Customer Order Header"=X,
        table "Posted Customer Order Line"=X,
        table "Posted Customer Order Payment"=X,
        report "Customer Order"=X,
        codeunit "Custom Extension Install"=X,
        codeunit "Custom Extension Upgrade"=X,
        codeunit "Custom Lookup State Manager"=X,
        codeunit "Customer Order Post"=X,
        codeunit "Event Mgmt."=X,
        codeunit "Report Layout Selection Mgmt."=X,
        page "Customer Order"=X,
        page "Customer Order Lines"=X,
        page "Customer Order Payment List"=X,
        page "Customer Order Payments"=X,
        page "Customer Order Subform"=X,
        page "Customer Orders"=X,
        page "Posted Cust Order Payment List"=X,
        page "Posted Customer Order"=X,
        page "Posted Customer Order Lines"=X,
        page "Posted Customer Order Subform"=X,
        page "Posted Customer Orders"=X;
}